# Auto-generated by IDE. All changes by user will be lost!
# Created at 1/18/13 7:24 PM

BASEDIR = $$_PRO_FILE_PWD_

INCLUDEPATH +=  \
    $$BASEDIR/src

SOURCES +=  \
    $$BASEDIR/src/gong.cpp \
    $$BASEDIR/src/main.cpp \
    $$BASEDIR/src/soundmanager.cpp

HEADERS +=  \
    $$BASEDIR/src/gong.h \
    $$BASEDIR/src/soundmanager.h

lupdate_inclusion {
    SOURCES += \
        $$BASEDIR/../assets/*.qml
}

TRANSLATIONS = \
    $${TARGET}.ts

